// generated by grok

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  // Optional: Add config like logging
  //log: ['query', 'info', 'warn', 'error'],
});

export default prisma;