"use client";
// generated by grok
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { PaperAirplaneIcon, BuildingOfficeIcon, ArrowRightIcon } from "@heroicons/react/24/outline";

export default function Home() {
  const [userName, setUserName] = useState<string | null>(null);
  const router = useRouter();

  useEffect(() => {
    const fetchUserProfile = async () => {
      const token = localStorage.getItem('accessToken');
      if (!token) return;

      try {
        // Decode the JWT token to get the user ID
        const payload = JSON.parse(atob(token.split('.')[1]));
        const userId = payload.user;

        const response = await fetch(`/api/protected/users/${userId}`, {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        if (response.ok) {
          const data = await response.json();
          setUserName(data.firstName);
        }
      } catch (error) {
        console.error('Error fetching user profile:', error);
      }
    };

    fetchUserProfile();
  }, []);

  const handleSearchFlights = () => {
    router.push('/flights');
  };

  const handleSearchHotels = () => {
    router.push('/hotels');
  };

  return (
    <div className="min-h-screen w-full bg-gradient-to-b from-white to-blue-50 dark:from-gray-900 dark:to-gray-800 transition-colors duration-300">
      <div className="container mx-auto px-4 py-12">
        <div className="flex flex-col items-center justify-center text-center mb-16">
          <div className="mb-8">
            <Image 
              src="/flynext-logo.png" 
              alt="FlyNext Logo" 
              width={120} 
              height={120} 
              className="mx-auto"
            />
          </div>
          <h1 className="text-5xl font-bold text-gray-900 dark:text-white mb-4 transition-colors duration-300">
            {userName ? `Welcome back, ${userName}!` : 'Welcome to FlyNext'}
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mb-8 transition-colors duration-300">
            Your one-stop platform for finding the perfect flights and hotels for your next adventure.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300 transition-colors duration-300">
            <div className="bg-gray-900 dark:bg-gray-700 p-6 text-white">
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <PaperAirplaneIcon className="h-8 w-8 mr-3" />
                  <h2 className="text-2xl font-bold">Search Flights</h2>
                </div>
                <ArrowRightIcon className="h-6 w-6" />
              </div>
            </div>
            <div className="p-6">
              <p className="text-gray-600 dark:text-gray-300 mb-6 transition-colors duration-300">
                Find the best flight deals to your dream destination. Compare prices, schedules, and airlines all in one place.
              </p>
              <button
                onClick={handleSearchFlights}
                className="w-full bg-gray-900 dark:bg-gray-700 text-white py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-600 transition-colors flex items-center justify-center"
              >
                <span>Search Flights</span>
                <ArrowRightIcon className="h-5 w-5 ml-2" />
              </button>
            </div>
          </div>

          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300 transition-colors duration-300">
            <div className="bg-teal-600 dark:bg-teal-700 p-6 text-white">
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <BuildingOfficeIcon className="h-8 w-8 mr-3" />
                  <h2 className="text-2xl font-bold">Search Hotels</h2>
                </div>
                <ArrowRightIcon className="h-6 w-6" />
              </div>
            </div>
            <div className="p-6">
              <p className="text-gray-600 dark:text-gray-300 mb-6 transition-colors duration-300">
                Discover comfortable accommodations for your stay. Browse by location, amenities, and price range.
              </p>
              <button
                onClick={handleSearchHotels}
                className="w-full bg-teal-600 dark:bg-teal-700 text-white py-3 px-4 rounded-lg hover:bg-teal-700 dark:hover:bg-teal-600 transition-colors flex items-center justify-center"
              >
                <span>Search Hotels</span>
                <ArrowRightIcon className="h-5 w-5 ml-2" />
              </button>
            </div>
          </div>
        </div>

        <div className="mt-16 text-center">
          <h2 className="text-3xl font-bold text-gray-800 dark:text-white mb-6 transition-colors duration-300">Why Choose FlyNext?</h2>
          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-300">
              <div className="text-blue-600 dark:text-blue-400 text-4xl mb-4 transition-colors duration-300">✈️</div>
              <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white transition-colors duration-300">Best Flight Deals</h3>
              <p className="text-gray-600 dark:text-gray-300 transition-colors duration-300">Find the most competitive prices on flights to destinations worldwide.</p>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-300">
              <div className="text-teal-600 dark:text-teal-400 text-4xl mb-4 transition-colors duration-300">🏨</div>
              <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white transition-colors duration-300">Quality Accommodations</h3>
              <p className="text-gray-600 dark:text-gray-300 transition-colors duration-300">Book hotels that match your preferences and budget.</p>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-300">
              <div className="text-purple-600 dark:text-purple-400 text-4xl mb-4 transition-colors duration-300">🔍</div>
              <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white transition-colors duration-300">Easy Search</h3>
              <p className="text-gray-600 dark:text-gray-300 transition-colors duration-300">Simple and intuitive search tools to find exactly what you need.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 